import { Ancestry, Trait } from "./Unit";

export class TraitDefinition {
    name: string
    description: string
    inherit: boolean
    newTrait: Trait | undefined

    constructor(name: string, description: string, inherit: boolean) {
        this.name = name;
        this.description = description;
        this.inherit = inherit;
        this.newTrait = undefined;
    }
}

export class AncestryDefinition {
    trait: Trait
    inherit: boolean

    constructor(trait: Trait, inherit: boolean) {
        this.trait = trait;
        this.inherit = inherit;
    }
}

export const TRAIT_DESCRIPTION_MAP = new Map<Trait, string>([
    [Trait.AAAUUUGH, "When this unit breaks, all adjacent units suffer 1 casualty."],
    [Trait.ADAPTABLE, "This unit has advantage on Morale and Command tests."],
    [Trait.AERIAL_BOMBARDMENT, "If this unit spends an activation doing nothing, it can use its next activation to target a fortification by making a DC 13 Power test. On a success, it deals 1d4 + 2 damage to the fortification."],
    [Trait.AMORPHOUS, "During an attack, this unit can move into another unit, occupying its space and engaging it. Then, it may move past units of that type, such as moving past infantry to attack archers, without disengaging."],
    [Trait.AMPHIBIOUS, "This unit does not suffer movement penalties when fighting underwater, or in rain or mud."],
    [Trait.ANTI_ARMOR, "Anti-armor units have advantage on Power checks against Heavy and Super-Heavy units."],
    [Trait.ANTI_INFANTRY, "Anti-infantry units have advantage on Power checks against targets that are smaller than a horse."],
    [Trait.ANTI_LARGE, "Anti-large units have advantage on Power checks against targets that are at least as large as a horse."],
    [Trait.ARCADIAN, "This unit has advantage on Power tests to resist battle magic."],
    [Trait.ARCHERS, "This unit can attack any opposed unit. Successful Power tests the unit makes against opposed units that are not exposed inflict only 1 casualty."],
    [Trait.ARMORED_CARAPACE, "This unit suffers no casualties from artillery Attack tests."],
    [Trait.BARBS, "An opposed infantry unit that makes a successful Power test as part of an attack against this unit suffers 1 casualty."],
    [Trait.BATTLE_HYMN, "This unit has a bonus to Morale equal to its commander’s domain size, as do allied units while adjacent to this unit."],
    [Trait.BEES, "If this unit inflicts a casualty on an enemy unit, that unit must make a DC 10 Morale check. If the unit is not diminished, failure only exhausts it. Immune to bees."],
    [Trait.BETTER_THAN_ONE, "When this unit attacks an opposed unit, it can also attack any other adjacent opposed unit."],
    [Trait.BIG, "This unit has advantage on Power tests against units whose casualties are lower than this unit’s."],
    [Trait.BLANKET_FIRE, "As an action, choose a rank on the battlefield. Attack each unit in that rank. Recharge 4—6."],
    [Trait.BLINDING, "When an opposed unit fails an Attack test against this unit, the opposed unit is disoriented."],
    [Trait.BRACING, "When this unit is not engaged and is attacked, it negates the effects of Charge."],
    [Trait.BRACING_AGAINST_LARGE, "When this unit is not engaged and is attacked by a large unit, it negates the effects of Charge."],
    [Trait.BRED_FOR_WAR, "This unit cannot be diminished, and cannot have disadvantage on Morale checks."],
    [Trait.BRUTAL, "This unit inflicts +1 casualties on a successful Power check."],
    [Trait.BURNING, "Each opposed unit that activates adjacent to this unit suffers 1 casualty."],
    [Trait.BURROW, "As an action, remove this unit from the battlefield. On its next activation, place the unit in any empty space. The unit is disoriented until the end of that activation."],
    [Trait.CAVALRY_UNIT, "This unit has the Cavalry unit type."],
    [Trait.CELESTIAL, "Once per battle, this unit has advantage on both its Attack and Power checks."],
    [Trait.CHAOS_VULNERABILITY, "This unit has disadvantage on Power tests to resist battle magic."],
    [Trait.CHARGE, "If this unit moves at least 1 space before it attacks, it has advantage on Attack tests for this activation as long as the target is in the direction the unit moved."],
    [Trait.CHARGE_DEFENSE, "When this unit is not engaged and receives a Charge, first it Attacks the enemy unit with advantage, then negates the effects of Charge."],
    [Trait.CHARGE_DEFENSE_AGAINST_LARGE, "When this unit is not engaged and receives a Charge from a large unit, first it Attacks the enemy unit with advantage, then negates the effects of Charge."],
    [Trait.CHORUS_OF_VICTORY, "As an action, choose a rank on the battlefield. Each allied unit in that rank increments its casualty die and has advantage on Attack tests until the end of its next activation. Recharge 6."],
    [Trait.CLOSE_RANGE, "This unit has advantage on Attack tests and Power tests against adjacent units."],
    [Trait.CLOUD_OF_DARKNESS, "Opposed units have disadvantage on Attack tests against this unit."],
    [Trait.COLLATERAL_DAMAGE, "When this unit makes a successful Power test against an infantry or artillery unit, the unit opposite the target also suffers 1 casualty."],
    [Trait.CONSUME, "As an action, choose an adjacent opposed unit with casualties lower than this unit's. That unit must succeed on a DC 15 Power test or break. Recharge 5-6."],
    [Trait.CORRODE, "When this unit makes a successful Attack test against an opposed unit, that unit takes -2 to Attack and Defense. Each opposed unit can be affected by this trait only once per battle."],
    [Trait.CORROSIVE_BREATH, "As an action, choose three adjacent opposed units. Each unit must succeed on a Power test (DC = 8 + this unit’s size) or suffer 2 casualties and gain one acid token. Recharge 5—6."],
    [Trait.COURAGEOUS, "Once per battle, this unit can choose to succeed on a Morale check it just failed."],
    [Trait.COWARDLY, "This unit suffers a -1 Morale penalty for each Morale check it has made in a round. If it does not meet DC 1 on any Morale check, it abandons the field."],
    [Trait.CREATE_DEAD, "If this unit causes an opposed unit to break, replace that unit with a Ghoul Infantry unit under the command of this unit’s commander."],
    [Trait.DAMAGE_RESISTANT, "Successful Attack tests against this unit inflict no casualties. Successful Power tests inflict casualties normally."],
    [Trait.DAMAGE_TYPES, "Certain damage types may affect this unit differently."],
    [Trait.DAYLIGHT_WEAKNESS, "While in direct sunlight, this unit has disadvantage on Power tests."],
    [Trait.DEAD, "This unit always succeeds on Morale tests, and cannot be diminished."],
    [Trait.DEFLECT, "This unit has +2 Defense against missile fire."],
    [Trait.DEMONIC, "Levy, Green, and Regular troops must pass a Morale check to engage this unit (failure only exhausts). Each enemy unit need only do this once."],
    [Trait.DIG, "As an action, choose a space containing an opposed fortification and remove this unit from the battlefield. On the unit’s next activation, the target fortification takes 2d6 damage and this unit breaks as though it were in that space."],
    [Trait.DIMINISHED, "When the unit suffers a casualty, it must make a DC 15 Morale check. If it fails, it immediately suffers another casualty."],
    [Trait.DIRE_HYENA_MOUNTS, "This unit has advantage on Attack tests against diminished units."],
    [Trait.DISENGAGE, "The unit can disengage as an action without making a Morale check."],
    [Trait.DISRUPTIVE, "When an opposed unit adjacent to this unit activates, it has a 25 percent chance of doing nothing on that activation."],
    [Trait.DRACONIC_ANCESTRY, "This unit cannot be disorganized or weakened, and it is immune to the Harrowing trait."],
    [Trait.DRAGONKIN, "If there is an allied dragon in the battle or if this unit’s commander has some sort of draconic ancestry, this unit has advantage on Attack tests, Command tests, and Morale tests."],
    [Trait.DRONE, "As an action, choose a rank on the battlefield. Each opposed unit in that rank must succeed on a DC 15 Power test or suffer 1 casualty and be unable to move on its next activation. This unit can use this trait only once per battle."],
    [Trait.ELFSHOT, "When this unit succeeds on a Power test as part of an attack, the target unit must succeed on a DC 10 Power test or become weakened until the end of its next activation."],
    [Trait.EMBIGGEN, "As a reaction to activating, this unit’s size increases to 8. Its casualty die becomes a d8 and is incremented twice. Until the end of its activation, the unit has advantage on Attack tests and Power tests. This unit can use this trait only once per battle."],
    [Trait.ENCOURAGE, "When this unit exhausts, it can grant +3 Morale to up to 2 nearby allied units, lasting until this unit refreshes."],
    [Trait.ETERNAL, "This unit cannot be horrified, and it always succeeds on Morale checks to engage an enemy unit."],
    [Trait.ETHEREAL, "This unit has +1 to movement. It can move through other units, but only if it can end its movement in an empty space. Other units do not gain bonuses to Defense from fortifications against this unit’s attacks."],
    [Trait.EXPENDABLE, "An army's Strength Advantage is not reduced by losses to expendable units. They are easily recruited and replenished."],
    [Trait.FADE, "After a successful Attack test, this unit can move back 1 space. Opposed units cannot use the Follow Up maneuver in response."],
    [Trait.FAST_SIEGE_WEAPON_HEAVY, "This unit can attack a fortification. It automatically hits (no Attack test or Power test needed) and deals 5 damage."],
    [Trait.FAST_SIEGE_WEAPON, "This unit can attack a fortification. It automatically hits (no Attack test or Power test needed) and deals 3 damage."],
    [Trait.FEARLESS, "This unit automatically succeeds on Morale tests."],
    [Trait.FEARSOME, "As a reaction to making an Attack test, this unit forces the target to succeed on a Morale test (DC = 8 + this unit’s size) or suffer 1 additional casualty."],
    [Trait.FEAST, "At the end of this unit’s activation, if any diminished unit is adjacent to it, increment this unit’s casualty die."],
    [Trait.FIENDISH, "Levy, Green, and Regular troops must pass a Morale check to engage this unit (failure only exhausts). Each enemy unit need only do this once."],
    [Trait.FIRE_BLAST, "As an action, this unit forces two adjacent opposed units to each make a DC 13 Power test. On a failure, a unit suffers 2 casualties. Recharge 5-6."],
    [Trait.FIRE_BREATH, "As an action, this unit forces three adjacent opposed units to each make a Power test (DC = 8 + this unit’s size). On a failure, a unit suffers 2 casualties and gains a fire token. Recharge 5-6."],
    [Trait.FIRE_IMMUNITY, "This unit does not suffer casualties from traits or other effects with ‘fire’ or ‘flame’ in their names, or from fire tokens."],
    [Trait.FLAMING_WEAPONS, "When this unit makes a successful Power test as part of an attack, it adds a fire token to the target in addition to the normal effects of the test."],
    [Trait.FLIGHT, "This unit does not suffer terrain penalties for fighting over rough terrain and can target any unit type."],
    [Trait.FOLLOW_THE_STANDARD, "When this unit succeeds on a Power test as part of an attack, each cavalry unit the unit’s commander controls can use a reaction to immediately make an attack against the target of the Power test."],
    [Trait.FRENZY, "If this unit diminishes an enemy unit, it immediately makes a free Attack against that unit."],
    [Trait.GUERRILLAS, "When this unit succeeds on an Attack test against any opposed infantry or artillery unit (but not siege weapons), that unit is disoriented."],
    [Trait.GULP, "As an action, this unit forces an opposed infantry or artillery unit (but not a siege engine) to make a DC 15 Power test. On a failure, the target unit is diminished (or is broken if it was already diminished). Recharge 5-6."],
    [Trait.HALLUCINATORY_SPORES, "As an action, this unit forces a legal target to make a DC 15 Power test. On a failure, the opposed unit attacks one of its own allied units of this unit’s choice on the opposed unit’s next activation."],
    [Trait.HARD_HATS, "This unit has +2 to Defense against attacks from aerial units."],
    [Trait.HARRIERS, "If this unit succeeds on a Power test as part of an attack, this unit becomes the target unit’s only legal target on its next activation."],
    [Trait.HARROWING, "Any opposed infantry, cavalry, or aerial unit must first succeed on a Morale test (DC = 10 + this unit’s tier) when it attacks this unit. On a success, the attacking unit is not affected by any unit’s Harrowing trait for the rest of the battle. On a failure, the attacking unit’s activation ends."],
    [Trait.HEROES_OF_THE_MYRIAD_WORLDS, "Once per battle as a bonus action, this unit can gain advantage on Attack tests and Power tests until the end of its activation."],
    [Trait.HOLY, "Undead and fiend units have disadvantage on Attack tests and Power tests against this unit."],
    [Trait.HONORABLE, "This unit cannot fail Morale checks while its casualty die shows a 1."],
    [Trait.HOP, "For its movement, this unit can move to any empty space on the battlefield."],
    [Trait.HORRIFY, "If this unit inflicts a casualty on an enemy unit, that unit must make a DC 15 Morale check. If the unit is not diminished, failure only exhausts it. Immune to horrified."],
    [Trait.HURL_ROCKS, "If this unit succeeds on a Power check, it inflicts 2 casualties. Against fortifications, it inflicts 1d6 casualties."],
    [Trait.IMMUNITY, "This unit has immunities to damage or status effects, according to its type."],
    [Trait.IMPLACABLE, "This unit cannot unwillingly be moved or teleported, and it can ignore any effects of terrain."],
    [Trait.INDISTINCT, "Attack tests for ranged attacks made against this unit have disadvantage."],
    [Trait.INEXORABLE, "This unit is immune to any effect that would hinder or stop its movement, or that would deny it the ability to use actions."],
    [Trait.INSPIRE_FEAR, "Whenever this unit leaves an opposed unit diminished, all goblinoid units in the same rank as this unit can immediately attack a legal target."],
    [Trait.INTO_THE_BREACH, "As a reaction when it successfully executes the Follow Up maneuver, this unit has +2 to Defense until the beginning of its next activation."],
    [Trait.INVISIBILITY, "This unit cannot be attacked until it successfully attacks an opposed unit."],
    [Trait.JAUNT, "In place of its movement, remove this unit from the battlefield. It returns to the space it left, or an unoccupied space of the GM’s choice if that space is occupied, at the start of its next activation. Recharge 5-6."],
    [Trait.LIFE_DRAIN, "Power checks against engaged units that succeed by 7 or more inflict an additional casualty. This unit then increments its casualty die."],
    [Trait.LIGHTNING_BREATH, "As an action, choose a rank on the battlefield. Each unit in that rank must succeed on a Power test (DC = 8 + this unit’s size) or suffer 2 casualties. Recharge 5-6."],
    [Trait.LIMITED_FLIGHT, "This unit benefits from the Flight trait only if its equipment rating is Medium or lower. (Flight: This unit does not suffer terrain penalties for fighting over rough terrain and can target any unit type.)"],
    [Trait.LOAD_THE_BONES, "While any diminished unit is adjacent to this unit, this unit has +2 damage against opposed fortifications."],
    [Trait.LONG_LIVED, "This unit automatically succeeds on its first Morale check either to Disengage or Rally."],
    [Trait.LONG_RANGED, "This unit gains +2 Defense against missile fire, unless the attacker is also Long-Ranged."],
    [Trait.MAGIC_RESISTANCE, "This unit has advantage on saving throws against spells, battle magic, and other magical effects."],
    [Trait.MAGIC_RESISTANT, "This unit has advantage on Power tests to resist battle magic."],
    [Trait.MAGICAL_ADEPTS, "As a bonus action, this unit forces an opposed unit to make a DC 13 Power Test. On a failure, allied units have advantage on Attack tests against the opposed unit until the end of the battle. Recharge 5-6."],
    [Trait.MANEUVER_EVASIVE_MANEUVERS, "As a reaction when an opposed artillery unit makes an Attack test against this unit, impose disadvantage on the opposed unit’s Attack test. Recharge 5-6."],
    [Trait.MANEUVER_FIRE, "As a reaction to a successful Power test made against a target unit, add a fire token to the target. Recharge 4-6."],
    [Trait.MANEUVER_HOLD_THE_LINE, "As a reaction to being diminished, this unit makes a DC 13 Command test. On a success, this unit ignores the casualties that caused it to become diminished, and is not diminished."],
    [Trait.MANEUVER_LANCERS_FLANK_THEM, "As a reaction when an opposed cavalry or aerial unit inflicts 1 or more casualties on an allied infantry or artillery unit, this unit makes a free attack against that opposed unit."],
    [Trait.MANEUVER_LAND_AND_CHARGE, "While this unit has the aerial type, it can use a bonus action to make a DC 11 Command test. On a success, this unit’s Power tests have +2 damage on this activation, but the unit’s type becomes cavalry for its next activation. At the end of its next activation, the unit regains the aerial type. Recharge 4-6."],
    [Trait.MANEUVER_PREY_ON_THE_WEAK, "As a reaction to an exposed opposed unit being diminished, this unit makes a DC 10 Command test. On a success, the unit makes an attack against the opposed unit."],
    [Trait.MANEUVER_RAM_THEM, "As an action, this unit targets an opposed cavalry unit and makes a DC 15 Command test. On a success, the target unit suffers 1 casualty and loses its next action."],
    [Trait.MANEUVER_DETONATE, "As an action, this unit deals 1d4 + 2 damage to an adjacent fortification. Recharge 3-6."],
    [Trait.MANEUVER_OUTFLANK, "As an action, move this unit into any empty space. Any opposed unit that executes the Follow Up maneuver in response has disadvantage on the Command test."],
    [Trait.MANEUVER_REPAIR, "As an action, a fortification this unit is on or adjacent to recovers 1d4 + 2 hit points, up to its starting hit points."],
    [Trait.MANEUVER_SPIT_UPON_THEIR_HORNS, "As a reaction to succeeding on a Power test made as part of an attack, this unit makes a DC 13 Command test. On a success, the target unit suffers 1 additional casualty."],
    [Trait.MANEUVER_STRAFE, "As a reaction to succeeding on a Power test made as part of an attack against an opposed artillery or infantry unit, this unit makes a DC 13 Command test. On a success, two adjacent opposed units in the same rank as the target unit each suffer 1 casualty."],
    [Trait.MANEUVER_TESTUDO, "As a reaction to suffering 1 or more casualties from an opposed artillery or aerial unit’s Attack test, this unit makes a DC 13 Command test. On a success, any opposed unit targeting this unit has disadvantage on Power tests until this unit’s next activation."],
    [Trait.MARTIAL, "If this unit succeeds on a Power check and its size is greater than the defending unit, it inflicts 2 casualties."],
    [Trait.MASS_PROTECTION_AGAINST_EVIL, "Any opposed infantry or artillery unit must succeed on a DC 15 Morale test to enter the vanguard rank of this unit’s side."],
    [Trait.MEAT_SHIELD, "This unit increases one Size (casualties carry over) from when it first engages until the end of battle. Its maximum Size is 1d12, which this ability can increase to 1d20."],
    [Trait.MELD, "As a reaction to a successful Attack test against an infantry or artillery unit, this unit can move into the target unit’s space. While this unit is in the target’s space, the target unit cannot move and can attack only this unit. Units attacking either unit in this space have a 50 percent chance of targeting the wrong unit."],
    [Trait.MINDLESS, "This unit cannot fail Morale checks."],
    [Trait.MOBILE, "This unit has advantage on the Command test when using the Follow Up maneuver, and can move back 2 spaces when using the Withdraw maneuver."],
    [Trait.NATURES_BOND, "When an allied infantry or artillery unit suffers 1 or more casualties, this unit can take the casualty instead. This unit must be adjacent to it."],
    [Trait.NONE, "This unit has no traits."],
    [Trait.NOXIOUS_FOG, "As an action, this unit places two poison tokens in each of 4 adjacent spaces. Any unit that moves into a space with one or more of these poison tokens or that activates there suffers 1 casualty per token. Each space loses one poison token at the end of this unit’s subsequent activations. Recharge 5-6."],
    [Trait.OBSCURING, "Once per battle, as an action, this unit can cause all ranged Attack checks against it to be made at disadvantage for two turns."],
    [Trait.PACK_TACTICS, "When an adjacent unit that also has this trait successfully uses the Follow Up maneuver, this unit can move into any empty space adjacent to this unit’s current position."],
    [Trait.PIKE_TRAINING, "This unit has advantage on the Command test for the Set for Charge maneuver."],
    [Trait.PIKE_WALL, "As a battle reaction when attacked or attacking, this unit gains Bracing and +1 Attack, Power, and Defense against a single unit. If it changes its target while already engaged, it makes a DC 13 Morale check. (Bracing: When this unit is attacked, it negates the effects of Charge.)"],
    [Trait.POINT_BLANK, "When this unit succeeds on a Power test as part of an attack against an adjacent unit, it inflicts 1 additional casualty."],
    [Trait.POISONOUS, "When this unit succeeds on a Power test as part of an attack, the target unit is also weakened until the end of its next activation."],
    [Trait.POISONOUS, "When this unit inflicts a casualty, the target unit must save against a DC 13 battle magic or be poisoned."],
    [Trait.POOL_OF_SOULS_BLOOD, "Any opposed infantry or artillery unit adjacent to this unit cannot leave its space."],
    [Trait.POWERFUL_CHARGE, "This unit gains +2 Attack and +2 Power on its Charge."],
    [Trait.QUADRUPED, "For its movement, this unit becomes a cavalry unit until the end of its activation. The unit leaves the grid and then returns to the space it left at the end of its activation (or to its army’s reserve rank if that space is occupied). Recharge 5-6."],
    [Trait.RAM_RIDERS, "When this unit succeeds on a Power test as part of an attack, the target unit must succeed on a followup DC 10 Power test or become disoriented until the end of its next activation."],
    [Trait.RAVENOUS, "While any enemy unit is diminished, this unit can spend a round feeding on the corpses to increment their casualty die. Cannot use while engaged, unless with a diminished unit."],
    [Trait.RECKLESS, "This unit can take disadvantage on any Attack test in order to have that Attack test inflict an additional 1 casualty."],
    [Trait.REFLECTOR, "When this unit fails a Power test against a wand, it can use a reaction to roll a d20. On a 10 or higher, this unit suffers no effect from the wand and the unit activating the wand suffers the effect instead."],
    [Trait.REGENERATE, "When this unit refreshes, increment its casualty die. This trait ceases to function if the unit suffers a casualty from battle magic."],
    [Trait.RELENTLESS, "As a reaction to suffering a casualty that would cause this unit to break, this unit makes a DC 13 Power test. On a success, this unit does not break and has 1 casualty."],
    [Trait.RESOLUTE, "This unit always succeeds on Morale tests."],
    [Trait.RIME, "Any opposed infantry or artillery unit adjacent to this unit has its movement reduced to 0 and cannot benefit from bonus movement."],
    [Trait.ROCK_HURLER, "If this unit succeeds on an attack check, it inflicts 2 casualties, against fortifications."],
    [Trait.ROCK, "As an action, this unit can make an Attack test against any opposed unit, with disadvantage if the target is an aerial unit. Recharge 4-6."],
    [Trait.ROCK_BREAKER, "This unit deals double damage against fortifications."],
    [Trait.ROLLING_THUNDER, "As an action, this unit makes an opposed Power test against an adjacent opposed unit. If this unit’s result is equal to or greater than the target’s, the target unit must move back 1 space or break. This unit immediately moves into the target unit’s vacated space."],
    [Trait.RUSH, "This unit automatically succeeds on the Command test for the Follow Up maneuver."],
    [Trait.SAVAGE, "This unit has advantage on the first Attack check it makes each battle."],
    [Trait.SCOURGE_OF_THE_WILD, "This unit has +2 to Attack and +2 to Power against orc, goblinoid, or elf units."],
    [Trait.SCOUTS, "This unit can deploy into the rear rank of an opposed army."],
    [Trait.SCREECH, "As an action, this unit forces an opposed unit to succeed on a DC 15 Power test or become misled. Recharge 4-6."],
    [Trait.SHIELDED, "This unit has +3 Defense against missile fire."],
    [Trait.SHOCK_TROOPS, "Each time this unit causes another unit to be diminished, this unit gains +2 to Attack and +2 to Power until the end of the battle."],
    [Trait.SHORT_RANGED, "This unit cannot attack archers if enemy infantry or cavalry remain on the field, unless that unit is also Short-Ranged."],
    [Trait.SIEGE, "This unit can attack fortifications and can be targeted as a siege unit."],
    [Trait.SIEGE_ENGINE, "This unit must spend 1 round of battle doing nothing before each attack. This unit can attack a fortification, it automatically hits (no Attack test or Power test needed) and deals 1d4 + 2 damage."],
    [Trait.SIEGE_UNIT, "This unit has the Siege Engine unit type and cannot have another type."],
    [Trait.SIEGE_WEAPON, "This unit can attack an adjacent fortification. It automatically hits (no Attack test or Power test needed) and deals 3 damage."],
    [Trait.SKIRMISH, "As an action, the unit prepares to Attack enemy units that attempt to engage nearby allies. After it attacks, it exhausts."],
    [Trait.SLAM, "When this unit succeeds on a Power test as part of an attack, the target unit is also disoriented."],
    [Trait.SLOW, "This unit cannot use two consecutive battle orders to Attack."],
    [Trait.SMOKE_SCREEN, "When this unit succeeds on an Attack test against another unit, that unit is also disoriented."],
    [Trait.SOLAR_FLARE, "Once per battle as a reaction to targeting a fortification, the damage this unit deals to fortifications is maximized, and it deals that damage to all fortifications in one rank."],
    [Trait.SOPORIFIC_SPORES, "As an action, this unit forces a legal target to make a DC 13 Power test. On a failure, the opposed unit is disorganized."],
    [Trait.SOW_CHAOS, "Each opposed unit within 1 space of this unit has disadvantage on Morale and Command tests, and suffers 1 additional casualty if it fails the Morale test to avoid becoming diminished."],
    [Trait.SPECIAL, "This unit's traits and abilities may negate or ignore those of other units, including resistances."],
    [Trait.SPIKE_SHOT, "As an action, this unit forces a target unit to succeed on a DC 12 Power test or suffer 2 casualties and become weakened. An affected unit can repeat this power test at the end of each of its activations to lose the weakened unit condition, Recharge 5—6."],
    [Trait.SPLIT, "When this unit is diminished, place an identical unit with the same current combat statistics and casualties in an empty adjacent space."],
    [Trait.SPORES, "When this unit is targeted by a successful Attack test from an infantry, cavalry, or aerial unit, the attacking unit must succeed on a DC 13 Power test or become disoriented."],
    [Trait.STALWART, "While this unit is diminished, opposed infantry and cavalry units have disadvantage on Power tests against it."],
    [Trait.STEALTH, "This unit starts each battle hidden. If not engaged, it can Hide as an action to attempt to become hidden. Hidden units cannot be attacked."],
    [Trait.STINKY, "Any opposed unit adjacent to this unit has disadvantage on Attack tests."],
    [Trait.STONE, "Each opposed unit that activates adjacent to this unit suffers 1 casualty."],
    [Trait.STONESKIN, "As a reaction to suffering 1 or more casualties from any opposed artillery unit, this unit can ignore 1 of those casualties."],
    [Trait.STRENGTH_DRAIN, "If this unit inflicts a casualty on an engaged unit, that unit loses 1 Power. Lost Power regenerates the next day."],
    [Trait.STRENGTH_IN_NUMBERS, "This unit begins the battle with 1 additional casualty for each other undead unit in its army."],
    [Trait.STUPID, "Each time it attacks, this unit has a 25 percent chance of ignoring its intended target and attacking a random adjacent unit."],
    [Trait.SWORDS_OF_THE_DRAGON_LORD, "When this unit makes a successful Attack test against a target unit, the target must succeed on a DC 13 Morale test or suffer 1 additional casualty."],
    [Trait.TO_THE_DEATH, "If this unit breaks as a result of an opposed unit’s Attack or Power test, the attacking unit suffers 1 casualty."],
    [Trait.TRAMPLE, "When this unit inflicts a casualty, it gains advantage on Attack checks against the same target for one round."],
    [Trait.TWISTING_ROOTS, "As an action, this unit can sap the walls of a fortification. Siege units have advantage on Power checks against sapped fortifications."],
    [Trait.UNDEAD, "Levy, Green, and Regular troops must pass a Morale check to engage this unit (failure only exhausts). Each enemy unit need only do this once."],
    [Trait.UNDERMINE, "As an action, this unit can sap the walls of a fortification. Siege units have advantage on Power checks against sapped fortifications."],
    [Trait.UNSOLDIERS, "This unit is comprised of untrained recruits and cannot have an Equipment or Experience rating, a unit type other than Levies, nor follow any special Orders on the battlefield."],
    [Trait.UNSTOPPABLE, "This unit's abilities and traits cannot be negated."],
    [Trait.VETERANS_OF_A_THOUSAND_WARS, "This unit’s movement increases by 1. When attacking units of a lower tier, its damage increases by 1."],
    [Trait.VULNERABILITY, "This unit has vulnerabilities to damage or status effects, according to its type."],
    [Trait.WAIL, "Once per battle, this unit can use an action to force each adjacent opposed unit to make a DC 15 Power test. On a failure, a unit suffers 1 casualty, and its Morale bonus is reduced to 0 until the end of its next activation. On a success, a unit has disadvantage on Morale tests until the end of its next activation."],
    [Trait.WARBRED, "As a reaction to succeeding on a Power test as part of an attack, this unit can make a DC 10 Command test. On a success, this unit can attack again."],
    [Trait.WAVE, "When this unit succeeds on a Power test as part of an attack against an opposed unit, the opposed unit is pushed back 1 space if there is an empty space behind it. If there is no empty space, the opposed unit and the unit behind it each suffer 1 casualty."],
    [Trait.WHIRLWIND, "When this unit succeeds on an Attack test against an opposed infantry unit, that unit takes -2 to Attack and Defense. Each opposed unit can be affected by this trait once per battle."],
    [Trait.YOU_FOLLOW, "Whenever this unit successfully uses the Follow Up maneuver, each goblinoid unit in the rank this unit leaves can move 1 space."]
]);

export const ANCESTRY_TRAIT_MAP = new Map<Ancestry, Trait[]>([
    [Ancestry.DRAGONBORN, [Trait.COURAGEOUS]],
    [Ancestry.DWARF, [Trait.STALWART]],
    [Ancestry.ELF, [Trait.ETERNAL]],
    [Ancestry.GIANT, [Trait.ROCK_HURLER]],
    [Ancestry.GHOUL, [Trait.UNDEAD, Trait.HORRIFY, Trait.RAVENOUS]],
    [Ancestry.GNOLL, [Trait.FRENZY]],
    [Ancestry.GNOME, []],
    [Ancestry.GOBLINOID, []],
    [Ancestry.HOBGOBLIN, [Trait.BRED_FOR_WAR, Trait.MARTIAL]],
    [Ancestry.HUMAN, [Trait.COURAGEOUS]],
    [Ancestry.KOBOLD, []],
    [Ancestry.LIZARDFOLK, [Trait.AMPHIBIOUS]],
    [Ancestry.OGRE, [Trait.BRUTAL]],
    [Ancestry.ORC, [Trait.SAVAGE]],
    [Ancestry.UNDEAD, [Trait.UNDEAD, Trait.MINDLESS]],
    // TODO Finish this
    [Ancestry.FIEND, []],
    [Ancestry.MONSTROUS, []],
    [Ancestry.SPECIAL, []],
    [Ancestry.TREANT, []],
    [Ancestry.TROLL, []]
]);